name: Protect Branches

on:
  workflow_dispatch: 

jobs:
  protect-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Protect Branches
        uses: actions/github-script@v6
        with:
          script: |
            const org = 'SwissWallet'; 
            const branch = 'master'; 
            const protectionSettings = {
              # required_status_checks: {
              #   strict: true,
              #   contexts: ["build"] 
              # },
              enforce_admins: true,
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 1
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false ,
            };

            const { data: repos } = await github.rest.repos.listForOrg({
              org: org,
              type: 'all'
            });

            for (const repo of repos) {
              try {
        
                await github.rest.repos.updateBranchProtection({
                  owner: org,
                  repo: repo.name,
                  branch: branch,
                  ...protectionSettings
                });
                console.log(`Branch ${branch} protegida no repositório ${repo.name}`);
              } catch (error) {
                console.error(`Erro ao proteger o branch ${branch} no repositório ${repo.name}:`, error);
              }
            }