name: Protect Branches

on:
  workflow_dispatch:

jobs:
  protect-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Protect Branches
        uses: actions/github-script@v6
        with:
          script: |
            const org = 'SwissWallet';
            const branch = 'master';
            const protectionSettings = {
              enforce_admins: true,
              required_pull_request_reviews: {
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                required_approving_review_count: 1
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false
            };

            try {
              const { data: repos } = await github.rest.repos.listForOrg({
                org: org,
                type: 'all'
              });

              if (repos.length === 0) {
                console.log(`No repositories found in organization ${org}.`);
                return;
              }

              for (const repo of repos) {
                try {
                  await github.rest.repos.updateBranchProtection({
                    owner: org,
                    repo: repo.name,
                    branch: branch,
                    ...protectionSettings
                  });
                  console.log(`Branch ${branch} protected in repository ${repo.name}`);
                } catch (error) {
                  console.error(`Error protecting branch ${branch} in repository ${repo.name}:`, error);
                }
              }
            } catch (error) {
              console.error('Error listing repositories:', error);
            }